### ISSUE TITLE
Broken React demo site

### ISSUE THREAD

**Issue by mingjunlu** [Ergosign/storybook-addon-pseudo-states#24]
**Describe the bug**
There seems to be an error causing the React demo site to crash.

**To Reproduce**
1. Go to [README of React](https://github.com/Ergosign/storybook-addon-pseudo-states/blob/master/src/react/README.md)
2. Click on [Live-Demo](https://philippone.github.io/create-react-app-storybook-addon-pseuo-states/)
3. See the error message
```
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bname%2C%20value%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bname%2C%20value%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Qg (https://philippone.github.io/create-react-app-storybook-addon-pseuo-states/vendors~main.7485033b14b621a5e3d6.bundle.js:2:1020337)
    at p (https://philippone.github.io/create-react-app-storybook-addon-pseuo-states/vendors~main.7485033b14b621a5e3d6.bundle.js:2:1021975)
    at ca (https://philippone.github.io/create-react-app-storybook-addon-pseuo-states/vendors~main.7485033b14b621a5e3d6.bundle.js:2:1023085)
    at https://philippone.github.io/create-react-app-storybook-addon-pseuo-states/vendors~main.7485033b14b621a5e3d6.bundle.js:2:1025168
    at R (https://philippone.github.io/create-react-app-storybook-addon-pseuo-states/vendors~main.7485033b14b621a5e3d6.bundle.js:2:1034566)
    at Rj (https://philippone.github.io/create-react-app-storybook-addon-pseuo-states/vendors~main.7485033b14b621a5e3d6.bundle.js:2:1074719)
    at Qj (https://philippone.github.io/create-react-app-storybook-addon-pseuo-states/vendors~main.7485033b14b621a5e3d6.bundle.js:2:1065354)
    at Kj (https://philippone.github.io/create-react-app-storybook-addon-pseuo-states/vendors~main.7485033b14b621a5e3d6.bundle.js:2:1065283)
    at yj (https://philippone.github.io/create-react-app-storybook-addon-pseuo-states/vendors~main.7485033b14b621a5e3d6.bundle.js:2:1062347)
    at Ig (https://philippone.github.io/create-react-app-storybook-addon-pseuo-states/vendors~main.7485033b14b621a5e3d6.bundle.js:2:1059139)
```

**Expected behavior**
The demo site should run without any error.

**Screenshots**
![截圖 2020-09-24 上午11 19 46](https://user-images.githubusercontent.com/40516784/94096914-e2dd8680-fe57-11ea-9cea-2c1a99538f9a.png)

**Desktop:**
 - OS: macOS Catalina 10.15.6
 - Browser:
    - Chrome 85.0.4183.102
    - Safari 14.0

**Comment by philippone** [comment]
Hi @mingjunlu ,

thanks for your feedback.

Demo page is now working.
